### ISSUE TITLE
Adding resources to lessons.

### ISSUE THREAD

**Issue by kwrl** [arve0/codeclub_lesson_builder#106]
I think we should be able to add resources/links to lessons, such as a youtube tutorials showing how the lessons can be solved etc.

**Comment by arve0** [comment]
something like

```
# section
bla bla

[yt:ID]

```

or

```
---
resources:
    -youtu.be/ID
    -gist.github.io/asdf
---
```

?

**Comment by arve0** [comment]
See also https://github.com/kodeklubben/oppgaver/pull/82/files line 33

**Comment by okpedersen** [comment]
I believe both the first options have their merits - the first would be nice if you wanted to use videos in the text (in the same way you're using an image) and the second would be useful for an "Additional resources"-section (and could possibly be included in the YAML-header?).

Regarding the iframe-option: This option is (probably?) already working, and wouldn't require much effort from us. It would however be more difficult to use for less technical task creators, and I believe either (or a combination) of the two first options would be better in the long run.

**Comment by arve0** [comment]
I will not put time into this. One should simply use a `.zip` and link to it. If special elements are needed, use HTML.
