### ISSUE TITLE
Run clean before force-build?

### ISSUE THREAD

**Issue by okpedersen** [arve0/codeclub_lesson_builder#111]
I got some unexpected results using the builder, which seemed to be caused by pre-generated webpages in the `build`-folder.

```zsh
./gulp clean
./gulp
```
solved the problem.

**Comment by arve0** [comment]
Running clean (alone, not in parallel) before the other tasks is a bit messy, code-wise. With forever, switching branches should behave somewhat OK. If you stumble upon this again, please note the steps to reproduce, the unwanted effect and I'll look into it.
