### ISSUE TITLE
Feature: Click to toggle hint

### ISSUE THREAD

**Issue by okpedersen** [arve0/codeclub_lesson_builder#128]
Many tasks would benefit from having the possibility to 'toggle' a hint. Currently the only possibility is to *always* show a hint:

    * Do x, y, z
          
        **Hint:** use a loop

which becomes:

* Do x, y, z
    
    **Hint:** use a loop

**Comment by arve0** [comment]
I'm looking into replacing pandoc with marked, which will make modifications like these trivial. Hopefully we get performance and OS compability benefits also.

**Comment by arve0** [comment]
Looks like markdown-it is the shit. It has an plugin system, with a lot of [plugins available](https://www.npmjs.com/browse/keyword/markdown-it-plugin).
