### ISSUE TITLE
Allow http links in playlists

### ISSUE THREAD

**Issue by tjesi** [arve0/codeclub_lesson_builder#134]
Is it possible to create a new "course" named "Hour of Code", where we have playlists named for example "first grade", "second grade" etc? The playlist would then contain projects from the other courses or links to other webpages. For example the playlists:

"first grade" would go to studio.code.org
"fourth grade" would contain projects in scratch
"sevent grade" would contain projects in python

**Comment by arve0** [comment]
As of now, unfortunately, lessons in playlists are [hardcoded with `.html`](https://github.com/arve0/codeclub_lesson_builder/blob/master/playlist.js#L50) ending. 

This should be easy to fix: Add a test which check if beginning is `http://`.

When this is fixed:
1. create a folder named `hour_of_code`
2. add `index.md` with `title: Hour of Code`
3. [optional] add logos, add `hour_of_code/playlists` folder
4. add `hour_of_code/playlists/name_of_your_playlist.txt` with links to the appropriate websites
5. profit?

Also, if one do not want playlists, but rather an index, one could add individual files for each resource. Ex:
- `frost_code_org.md`, with `title` and `external` YAML-tag:
```
---
title: Frost
external: http://code.org/frost
---
```

**Comment by arve0** [comment]
For an example to playlists, see https://github.com/arve0/oppgaver/tree/master/src/scratch/playlists

**Comment by arve0** [comment]
I will not implement this, as this will not allow for metadata like title, level, etc.

**Comment by gahjelle** [comment]
Agreed, the solution is to use simple .md-files only with a yaml-header as above (the frost example), possibly with an added `external: False` if the link should be only in the playlist.

**Comment by arve0** [comment]
`indexed: false` :wink:

**Comment by gahjelle** [comment]
ahh, some wires got crossed .. :stuck_out_tongue:  Edited!
