### ISSUE TITLE
Other resources

### ISSUE THREAD

**Issue by tjesi** [arve0/codeclub_lesson_builder#136]
In a while there are going to be a lot of resources available, and we should prioritize what to show and what not to show at the front page. 

One suggestion is that we both have the following at the front page:
1. our own course-material.
 - Scratch, Python etc
2. combinations. 
- ex. when clicking Arduino, you currently go to Kodegenets Arduino course, but should go to a page where you can choose between different Arduino-resources, including Kodegenet.
3. others.
- "Andre ressurser" which goes to a page where you can click at ex. "Code.org" and get redirected to studio.code.org etc.

Ideas?

**Comment by arve0** [comment]
I guess when getting a lot of resources one can combine them in a course, e.g. Arduino. Then "Bygg en radiobil - Kodegenet" is a lesson with specified difficulty. To further differentiate, one can add a icon([like glyphicon-new-window](http://getbootstrap.com/components/#glyphicons-glyphs)) showing that the resource is external.

One can also create a single course name "External" and put everything there.

Further then those approach, one will need to think about UI and organization, which will be opinionated if one does not have any numbers to lay on (we have x users on the python course, y users leave our page after 30 seconds, etc).

Maybe this discussion more appropriate in [kodeklubben/oppgaver](/kodeklubben/oppgaver)?
