### ISSUE TITLE
Intro keeps asking after No

### ISSUE THREAD

**Issue by gahjelle** [arve0/codeclub_lesson_builder#163]
Tried kodeklubben.github.io today in IE. The intro tour asks if I want the tour. If I say no, it keeps asking on every page I visit.

**Comment by arve0** [comment]
Hm. [js-cookie](https://github.com/js-cookie/js-cookie) has been used for storing cookies, and it reports supporting IE 6-11. Which version are you using?

Can you try this in [console](http://stackoverflow.com/questions/2656730/internet-explorer-console?answertab=votes#tab-top):

```js
>> window.Cookie.get('last visit') 
"2015-11-06T11:06:37+01:00" 
```

**Comment by arve0** [comment]
What is the exact text of the question? Can be that [this test](https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/intro.js#L38) fails, somehow.

**Comment by gahjelle** [comment]
Unfortunately this just happened when I was demoing using a couple of borrowed machines at a school (it happened on all of them), so I am not sure of the version or the exact text. I'll let you know if I see it again.

**Comment by arve0** [comment]
A "solution": be less intrusive. It might just be the computers had a strict security policy, not storing cookies.

A less intrusive method could be a tooltip/popup, instead of a modal.

**Comment by arve0** [comment]
Another solution, assuming cookie-saving fails:

```js
Cookie.set('test', '1234');
if (Cookie.get('test') !== '1234') {
  // cookies does not work
}
```
