### ISSUE TITLE
Search-boksen står skjevt i forhold til Home

### ISSUE THREAD

**Issue by NorwegianKiwi** [arve0/codeclub_lesson_builder#175]
<img width="1205" alt="screen shot 2015-12-15 at 23 11 39" src="https://cloud.githubusercontent.com/assets/8851134/11826768/88bfef6a-a387-11e5-90b6-9e66afc410e4.png">

Search-boksen i meny-linjen står skjevt i forhold til Home-knappen. Muligens fordi LKK-lenken er tatt bort.

Vil også nevne at den lille versjonen av KodeTimen-ikonet ikke er alignet på samme måte som de andre ikonene (teksten under er f.eks. mye høyere oppe).

Screenshot var tatt på Chrome på OSX (mac) Version 46.0.2490.86 (64-bit), og codeclub_lesson_builder bygget fra commit 3310724 (p.t. HEAD på master).

**Comment by arve0** [comment]
Sinner: https://github.com/arve0/codeclub_lesson_builder/commit/4822d55b4d076926cae3ba1b72c19de023996a56#diff-82712801bc85ac5cda3d490118444fc7R273

Regarding kodetimen logo, this is a special case for the norwegian build as of now, to draw attention. In general, logos should be square. A logo-container could force this.
