### ISSUE TITLE
Showing plaintext only

### ISSUE THREAD

**Issue by Jxr227** [arve0/codeclub_lesson_builder#196]
Hi Sorry to bother you again,

So now I'm trying to create my own resources but it's only showing as plain text. If I copy and paste the "Balloons" example into an md file, gulp will first produce everything correctly and the structure is there. As soon as I try to edit it to make it what I want it reloads as just plain text. 

For instance, the exact same file but with the div class ='scratch-preview' html block removed from the introduction, it will just load the plain text. Any idea why?

**Comment by arve0** [comment]
> Hi Sorry to bother you again,

No worries :smile: 

>  As soon as I try to edit it to make it what I want it reloads as just plain text.

Can you give me an example? A [gist](https://gist.github.com/) would be lovely.

> For instance, the exact same file but with the div class ='scratch-preview' html block removed from the introduction, it will just load the plain text. Any idea why?

It's the code blocks you're having trouble with? They need to be using the [scratch layout](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/scratch.jade) to include the scripts that convert code to blocks.

**Comment by arve0** [comment]
Btw, the layout can be defined directly in the file:

```
---
title: A scratch project
layout: scratch.jade
---
```

Or in [build.js](https://github.com/arve0/codeclub_lesson_builder/blob/master/build.js#L26-L33)

**Comment by Jxr227** [comment]
Ahh the issue may have been the "layout" missing from the md file. It has stylehseet: in there but not layout. Seems to be working so far with it. Hopefully it stays this way!

**Comment by Jxr227** [comment]
Okay yeah that seems to have fixed it silly me.

One last question whilst I'm here is would it be easy for me to define my own blocks with their own colour? I'm sure it's trivial and if I looked into it it wouldn't be a hassle to figure out but anyway. The exercises are to compliment a scratchX project I've created so I need the dark blue "More blocks" type with my own blocks.

Thanks for all of your help, you've been extremely helpful.

**Comment by arve0** [comment]
>  It has stylehseet: in there but not layout. 

`stylesheet` is not needed, it's not used.

>  would it be easy for me to define my own blocks with their own colour

I'm not sure. The scratch-blocks are done by some software called [scratchblocks](https://github.com/tjvr/scratchblocks). [Here](https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/scratch.jade#L7-L9) is the initialization of scratchblocks. Maybe @gahjelle know something about setting colors on blocks?

I know the documention is a bit poor, so just ask if something else doesn't work.

**Comment by gahjelle** [comment]
Hey,

You can change the color and shape of the scratch blocks using the notation `do [something v] :: motion`. This will create a custom blue motion block. I am not sure what you'll put after the `::` for scratchX blocks, but it seems like you can experiment with colors as well.

More info and examples at http://wiki.scratch.mit.edu/wiki/Block_Plugin/Syntax#Color_and_Shape_Changing (section 7)

Good luck!

**Comment by Jxr227** [comment]
Awesome, thanks for the help! I don't have the time to test this now but it's a method for doing it so i'll mark this as closed so as to not leave an open issue here :P Thanks so much for the help, both of you.
