### ISSUE TITLE
Remove license and header

### ISSUE THREAD

**Issue by Jxr227** [arve0/codeclub_lesson_builder#204]
Hi, very sorry to bother you (One last time I promise)

I've got everything working to my standard, but on the PDFs it has the header saying the name of the task, two download buttons and the KodeKlubben logo, could you point me in the direction of making this only show the Task name?

Also Similarly I'd need to remove the license information at the bottom to use these PDFs

thanks!

**Comment by arve0** [comment]
> PDFs it has the header saying the name of the task, 

https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson.jade#L8

> two download buttons 

https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson.jade#L23-L29

> and the KodeKlubben logo, 

https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson.jade#L6-L7

> could you point me in the direction of making this only show the Task name?

Adjust (remove) the layout on the lines shown above.

> Also Similarly I'd need to remove the license information at the bottom to use these PDFs

https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/layout.jade#L64-L77

**Comment by Jxr227** [comment]
That's done it perfectly. Thank you!

I have to say, all of your responses have been so helpful and concise, and I'm so sorry to have been such a bother throughout using this!

Thanks again

**Comment by arve0** [comment]
No problem:-)
