### ISSUE TITLE
Add Scratch colors to code styles

### ISSUE THREAD

**Issue by gahjelle** [arve0/codeclub_lesson_builder#52]
In Scratch projects inline code is marked up like for instance `if on edge, bounce`{.blockblue} to get proper coloring. These styles are currently missing.

We should support all colors from the old formatter: grey, lightgrey, orange, purple, pink, blue, lightblue, yellow, green and lightgreen.

In addition, some colors were missing and should be added: brown (events), darkpurple (more blocks), darkgrey (extensions).

**Comment by andylolz** [comment]
I’d suggest using `{.blockevent}` for events, `{.blockextensions}` for extensions etc, rather than each contributor trying to decide what colour a particular block is.

I added these to the lesson_format css, but I’ve yet to go through scratch projects updating them.

**Comment by arve0** [comment]
We did add the "action"-name: #57

2015-01-29 15:12 GMT+01:00 Andy Lulham <notifications@github.com>:

**Comment by andylolz** [comment]
Excellent.
