### ISSUE TITLE
Remove bottom lines in .flag and .save environments

### ISSUE THREAD

**Issue by gahjelle** [arve0/codeclub_lesson_builder#53]
When making headlines with the {.flag} or {.save} styles, horizontal lines are drawn both above and below the environment. This seems a bit too busy, it would probably be enough with just the line above the headline.

**Comment by arve0** [comment]
Should be fixed in #51.

**Comment by gahjelle** [comment]
The PR only seems to add space, not remove the line?

**Comment by arve0** [comment]
Correct, [removed](https://github.com/arve0/codeclub_lesson_builder/commit/073f12d4b03a8c0e42753d773654199c17115b1f) the bottom lines too.

**Comment by arve0** [comment]
fixed in #51
