### ISSUE TITLE
scratchblocks2 inline

### ISSUE THREAD

**Issue by arve0** [arve0/codeclub_lesson_builder#82]
@gahjelle Is there a reason why we should use {.blockmotion} etc, when inline exists? https://github.com/blob8108/scratchblocks2#inline-blocks

Haven't tried it, but I guess all inline blocks can be changed to something like <code>`turn ccw (10)`{.blocks}</code>.

**Comment by gahjelle** [comment]
Hmm... haven't seen the inline option before. That would probably be much better than what we are doing today with {.blockmotion} and friends. Let's try it out!

**Comment by andylolz** [comment]
Interesting – I hadn’t seen this either!

**Comment by arve0** [comment]
Will need some extra css, or the code will be on a line of its own.

**Comment by arve0** [comment]
Closed in #167. Usage:

```md
bla bla bla `when flag clicked`{.b} bla bla
```
