### ISSUE TITLE
Add difficulty and type of project to header?

### ISSUE THREAD

**Issue by gahjelle** [arve0/codeclub_lesson_builder#87]
Can we add the type of project (scratch, python etc) to the header so that it will be easy to see the type without knowing the project itself?

Also, add the difficulty-icon to the header.

**Comment by arve0** [comment]
I think `collection.name` already should be available, so it's a matter of adding images in the lesson+scratch template and styling them to fit at top right.

**Comment by arve0** [comment]
Fixed in #99: http://arve0.github.io/oppgaver/python/bokstaver/bokstaver.html
