### ISSUE TITLE
Monospaced font in code listings in pdf

### ISSUE THREAD

**Issue by gahjelle** [arve0/codeclub_lesson_builder#91]
A fixed width (monospaced) font will make the code listings easier to read. We currently use that in the HTML, but not in the PDF.

**Comment by arve0** [comment]
Its because phantomjs does not support web fonts. Font for code blocks
should be set to a system installed font which is mono spaced. This will of
course be different from system to system, so we might need to specify
several fonts to get predictable outcome on all systems.

**Comment by arve0** [comment]
Hm, was not set to web fonts after all. Seems to be a bug in PhantomJS. When phantom cannot find the first font listed in `font-family`, it picks the standard font. Which means this will break depending on which system the PDFs are built, unless we choose a font which are on all systems: **Courier**. In courier zero and O is very similar, so suggesting we take "Ubuntu Mono" as the first font, and let PDF build break on systems without `ttf-ubuntu-font-family` installed.

**Comment by gahjelle** [comment]
I agree that making the "official" pdfs should be the first priority. Let us use Ubuntu Mono.

I guess we can still add some alternative fonts so that things will start working properly once the PhantomJS bug is fixed, and then possibly a small note in a README somewhere about the bug and instructions for changing the font for other systems?

**Comment by arve0** [comment]
https://github.com/earaujoassis/ubuntu-fontface
